# serverless deploy
# serverless remove
service: graphql
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 128
functions:
  graphql:
    handler: index.graphql
    events:
      - http:
          path: /
          method: any
